package com.example.baseline.utils.python;

enum ManagedPythonFailureCategory {
    QUEUE_SATURATED,
    QUEUE_TIMEOUT,
    POOL_UNAVAILABLE,
    REQUEST_TIMEOUT_PRE_TRANSMISSION,
    REQUEST_TIMEOUT_POST_TRANSMISSION,
    PROCESS_EXIT,
    SOCKET_EOF,
    SOCKET_READ_FAILURE,
    SOCKET_WRITE_FAILURE,
    PROTOCOL_CORRUPTION,
    UNKNOWN_RESPONSE_ID,
    CAPACITY_MISMATCH,
    HEALTH_CHECK_TIMEOUT,
    HEALTH_CHECK_PROTOCOL_FAILURE,
    STARTUP_TIMEOUT,
    STARTUP_FAILURE,
    READINESS_MALFORMED,
    READINESS_CAPACITY_MISMATCH,
    RESTART_EXHAUSTED,
    SHUTDOWN_TIMEOUT,
    SHUTDOWN_INTERRUPTED,
    FORCED_TERMINATION,
    CLEANUP_FAILURE
}
